owner: calponia # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

# configure footer: https://upptime.js.org/docs/faq#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website
i18n:
  footer: © 2025 [ETAS GmbH](https://policies.pantaris.io/corporate-information), [Privacy Statement](https://policies.pantaris.io/policies/privacy)

# Issues are automatically closed once they are resolved, however if they are open for less than 15 minutes they are deleted instead.
# This disables the automatic deletion of issues, so that they can be reviewed by the developers.
skipDeleteIssues: true

# small, github hosted runner. It is free for us, because this is a public repository
runner: ubuntu-latest 

# adjust workflow schedules
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *" # this adjusts the frequency of the url monitors: max every 5 minutes

status-website:
  name: Cloud Hub Status
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pantaris.io
  # baseUrl: /status-page-poc2
  navbar:
    - title: Home
      href: https://pantaris.io
    - title: Workspace
      href: https://project.pantaris.io
    - title: Contact & Support
      href: https://documentation.pantaris.io/support/contact
  # custom css and styling
  ## without cname
  # themeUrl: https://calponia.github.io/status-page-poc2/etas-theme.css
  # logoUrl: https://calponia.github.io/status-page-poc2/logo_white.svg
  # favicon: https://calponia.github.io/status-page-poc2/favicon.png
  ## with cname
  themeUrl: https://status.pantaris.io/etas-theme.css
  logoUrl: https://status.pantaris.io/logo_white.svg
  favicon: https://status.pantaris.io/favicon.png
  links:
    - rel: stylesheet
      ## without cname
      # href: https://calponia.github.io/status-page-poc2/custom.css
      ## with cname
      href: https://status.pantaris.io/custom.css

# configuration of monitoring endpoints: https://upptime.js.org/docs/configuration#endpoints
sites:

  - name: Login & user settings
    url: https://my.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Projects (legacy)
    url: https://platform.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Projects
    url: https://project.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Organizations
    url: https://organization.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Creator
    url: https://portal.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Service catalog
    url: https://marketplace.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Documentation
    url: https://documentation.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Policies
    url: https://policies.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Support
    url: https://helpspot.calponia.com
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "<title>Calponia</title>"

  - name: Operations
    url: https://management-v2.pantaris.io
    expectedStatusCodes:
      - 200

  - name: CDN
    url: https://cdn.pantaris.io
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "<h1>Calponia CDN</h1>"

  - name: Upload & Webdav Service
    url: https://upload.pantaris.io/healthcheck
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "{\"data\":{\"code\":\"OPERATIONAL\"}}"

  - name: Download Service
    url: https://download.pantaris.io/healthcheck
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "{\"data\":{\"code\":\"OPERATIONAL\"}}"

  - name: Container services - General
    url: https://status-gateway.pantaris.io/v1/status/app-operator
    expectedStatusCodes:
      - 200

  - name: Container services - Build
    url: https://status-gateway.pantaris.io/v1/status/apphandler
    expectedStatusCodes:
      - 200

  - name: Container services - Startup
    url: https://service-startup.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Container services - External Traffic
    url: http://0ca2d4b8f342a21cfb6de71d1d1c46b4.ext.pantaris.io:3001/
    expectedStatusCodes:
      - 200

  - name: Container services - Registry
    url: https://docker.pantaris.io
    expectedStatusCodes:
      - 200

  - name: Version Control
    url: https://status-gateway.pantaris.io/v1/status/gitserver
    expectedStatusCodes:
      - 200

  - name: API v2
    url: https://api.pantaris.io/v2/healthcheck
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "{\"data\":{\"code\":\"OPERATIONAL\"}}"

  - name: Windows application streaming
    url: https://status-gateway.pantaris.io/v1/status/appstream
    expectedStatusCodes:
      - 200

  - name: User account inactivity
    url: https://status-gateway.pantaris.io/v1/status/user-inactivity
    expectedStatusCodes:
      - 200

  - name: Message Bus
    url: https://status-gateway.pantaris.io/v1/status/management-rabbitmq
    expectedStatusCodes:
      - 200

  - name: Logs Monitoring
    url: https://status-gateway.pantaris.io/v1/status/kibana
    expectedStatusCodes:
      - 200

  - name: Metrics Monitoring
    url: https://grafana.mon.pantaris.io
    expectedStatusCodes:
      - 401
